name: metrics
on:
  push:
    schedule:
      -cron: "0 0 * * *"
    push:
      branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: qupa-project
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_projects: yes
          plugin_projects_limit: 4

          plugin_repositories: 100
          plugin_repositories_forks: no
          plugin_repositories_affiliations: owner, collaborator
          plugin_repositories_skipped: qupa-project/qupa-project
          plugin_repositories_batch: 100

          plugin_lines: yes

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_traffic: yes

          plugin_support: yes
          plugin_sponsors: no

          plugin_notable: yes
          plugin_notable_repositories: yes
          config_order: base.header, introduction, base.repositories, language, projects, repositories, traffic, followup, languages, support, sponsors